# Extract and Consolidate Tables from Word Document

This notebook extracts tables from the Word document and consolidates them into a single CSV file.

In [ ]:
!uv pip install python-docx

Using Python 3.11.14 environment at: /home/abhishek/Documents/heatpump_ai_2/climate_data_prep/.venv
Resolved 3 packages in 109ms
Installed 1 package in 23ms
 + python-docx==1.2.0

In [1]:
from docx import Document
import csv
import os
import pandas as pd
from pathlib import Path

In [2]:
import os
import csv
from docx import Document


def is_category_row(cells):
    non_empty = [c for c in cells if c]
    return len(non_empty) >= 1 and len(set(non_empty)) == 1


def extract_tables_to_csv(docx_path, output_dir):
    if not os.path.exists(output_dir):
        os.makedirs(output_dir)

    document = Document(docx_path)

    for table_index, table in enumerate(document.tables, start=1):
        csv_path = os.path.join(output_dir, f"table_{table_index}.csv")

        current_category = None
        header_written = False

        with open(csv_path, mode="w", newline="", encoding="utf-8") as csv_file:
            writer = csv.writer(csv_file)

            for row in table.rows:
                cells = [
                    cell.text.replace("\n", " ").strip()
                    for cell in row.cells
                ]

                # ✅ FINAL category detection
                if is_category_row(cells):
                    current_category = cells[0]
                    continue

                # Skip fully empty rows
                if not any(cells):
                    continue

                # Write header once
                if not header_written:
                    writer.writerow(["Kategorie"] + cells)
                    header_written = True
                    continue

                # Write data row
                writer.writerow([current_category] + cells)

        print(f"Saved: {csv_path}")

In [3]:
# Configuration
DOCX_FILE = "beg_waermepumpen_pruef_effizienznachweis.docx"
OUTPUT_BASE_DIR = "/mnt/d/heatpump_data/heatpump_table"
OUTPUT_DIR = os.path.join(OUTPUT_BASE_DIR, "tables_csv")
CONSOLIDATED_CSV = os.path.join(OUTPUT_BASE_DIR, "consolidated_table_1.csv")

# Create output directory if it doesn't exist
os.makedirs(OUTPUT_BASE_DIR, exist_ok=True)
os.makedirs(OUTPUT_DIR, exist_ok=True)

# Extract tables to separate CSVs
extract_tables_to_csv(DOCX_FILE, OUTPUT_DIR)

Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_1.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_2.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_3.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_4.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_5.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_6.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_7.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_8.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_9.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_10.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_11.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_12.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_13.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_14.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_15.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_16.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_17.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_18.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_19.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_20.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_21.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_22.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_23.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_24.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_25.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_26.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_27.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_28.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_29.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_30.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_31.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_32.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_33.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_34.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_35.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_36.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_37.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_38.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_39.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_40.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_41.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_42.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_43.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_44.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_45.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_46.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_47.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_48.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_49.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_50.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_51.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_52.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_53.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_54.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_55.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_56.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_57.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_58.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_59.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_60.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_61.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_62.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_63.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_64.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_65.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_66.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_67.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_68.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_69.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_70.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_71.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_72.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_73.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_74.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_75.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_76.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_77.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_78.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_79.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_80.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_81.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_82.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_83.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_84.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_85.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_86.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_87.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_88.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_89.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_90.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_91.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_92.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_93.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_94.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_95.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_96.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_97.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_98.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_99.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_100.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_101.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_102.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_103.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_104.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_105.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_106.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_107.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_108.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_109.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_110.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_111.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_112.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_113.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_114.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_115.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_116.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_117.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_118.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_119.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_120.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_121.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_122.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_123.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_124.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_125.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_126.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_127.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_128.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_129.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_130.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_131.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_132.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_133.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_134.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_135.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_136.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_137.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_138.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_139.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_140.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_141.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_142.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_143.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_144.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_145.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_146.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_147.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_148.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_149.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_150.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_151.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_152.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_153.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_154.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_155.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_156.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_157.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_158.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_159.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_160.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_161.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_162.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_163.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_164.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_165.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_166.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_167.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_168.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_169.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_170.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_171.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_172.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_173.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_174.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_175.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_176.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_177.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_178.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_179.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_180.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_181.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_182.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_183.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_184.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_185.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_186.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_187.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_188.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_189.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_190.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_191.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_192.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_193.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_194.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_195.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_196.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_197.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_198.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_199.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_200.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_201.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_202.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_203.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_204.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_205.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_206.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_207.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_208.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_209.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_210.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_211.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_212.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_213.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_214.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_215.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_216.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_217.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_218.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_219.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_220.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_221.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_222.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_223.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_224.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_225.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_226.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_227.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_228.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_229.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_230.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_231.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_232.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_233.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_234.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_235.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_236.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_237.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_238.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_239.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_240.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_241.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_242.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_243.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_244.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_245.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_246.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_247.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_248.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_249.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_250.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_251.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_252.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_253.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_254.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_255.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_256.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_257.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_258.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_259.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_260.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_261.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_262.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_263.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_264.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_265.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_266.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_267.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_268.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_269.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_270.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_271.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_272.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_273.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_274.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_275.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_276.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_277.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_278.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_279.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_280.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_281.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_282.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_283.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_284.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_285.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_286.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_287.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_288.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_289.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_290.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_291.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_292.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_293.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_294.csv
Saved: /mnt/d/heatpump_data/heatpump_table/tables_csv/table_295.csv

In [5]:
import os

for i in (1, 2):
    path = os.path.join(OUTPUT_DIR, f"table_{i}.csv")
    if os.path.exists(path):
        os.remove(path)

In [7]:


# Translation mapping from German to English headers
header_translation = {
    'Kategorie': 'Category',
    'Hersteller': 'Manufacturer',
    'Typ': 'Type',
    'Niedertemperatur- Anwendung 35 °C': 'Low Temperature Application 35 C',
    'Niedertemperatur- Anwendung 35 °C.1': 'Low Temperature Application 35 C COP',
    'Niedertemperatur- Anwendung 55 °C': 'Low Temperature Application 55 C',
    'Niedertemperatur- Anwendung 55 °C.1': 'Low Temperature Application 55 C COP',
    'Kältemittel': 'Refrigerant',
    'Verfügbarkeit (Siehe Hinweis auf Seite 5)': 'Availability',
    'Verfügbarkeit (Siehe Hinweis auf Seite 5).1': 'Availability (2)'
}

def translate_header(german_header):
    if german_header in header_translation:
        return header_translation[german_header]
    for de, en in header_translation.items():
        if de in german_header or german_header in de:
            return en
    return german_header


csv_files = sorted(Path(OUTPUT_DIR).glob("table_*.csv"))

if not csv_files:
    print("No CSV files found!")
else:
    print(f"Found {len(csv_files)} CSV files to consolidate")

    # --- First pass: determine max column count and reference header ---
    max_cols = 0
    reference_header_german = None

    for csv_file in csv_files:
        df = pd.read_csv(csv_file, encoding="utf-8")
        max_cols = max(max_cols, len(df.columns))

    # Expecting 10 columns now (Kategorie + 9 data columns)
    for csv_file in csv_files:
        df = pd.read_csv(csv_file, encoding="utf-8")
        if len(df.columns) == max_cols:
            reference_header_german = df.columns.tolist()
            print(f"Using reference header from {csv_file.name}")
            break

    reference_header = [translate_header(h) for h in reference_header_german]

    print(f"Maximum columns found: {max_cols}")
    print(f"Reference header (German): {reference_header_german}")
    print(f"Reference header (English): {reference_header}\n")

    # --- Second pass: consolidate ---
    dataframes = []

    for csv_file in csv_files:
        df = pd.read_csv(csv_file, encoding="utf-8")
        original_num_cols = len(df.columns)
        
        # Translate headers first
        translated_headers = [translate_header(h) for h in df.columns]
        
        # Create a mapping from translated headers to their positions in reference_header
        # This ensures columns are placed in the correct positions
        column_mapping = {}
        for i, col in enumerate(translated_headers):
            if col in reference_header:
                column_mapping[col] = i
        
        # Create new dataframe with correct column order and missing columns filled
        new_data = {}
        num_rows = len(df)
        for ref_col in reference_header:
            if ref_col in column_mapping:
                # Column exists, use it
                new_data[ref_col] = df.iloc[:, column_mapping[ref_col]].values
            else:
                # Column is missing, add empty column with correct length
                new_data[ref_col] = [""] * num_rows
        
        df_aligned = pd.DataFrame(new_data)
        df_aligned.columns = reference_header

        # --- Header row detection (skip Category column!) ---
        header_values = [str(x).strip().lower() for x in reference_header[1:]]

        rows_to_drop = []
        for idx in range(min(2, len(df_aligned))):
            row_values = [
                str(x).strip().lower()
                for x in df_aligned.iloc[idx].tolist()[1:]  # skip Category
            ]

            keyword_hits = sum(
                1 for v in row_values
                if any(k in v for k in ['hersteller', 'typ', 'wärme', 'etas', 'refrigerant',
                                        'availability', 'manufacturer', 'type', 'heat'])
            )

            if keyword_hits >= 3:
                rows_to_drop.append(df_aligned.index[idx])

        if rows_to_drop:
            df_aligned = df_aligned.drop(index=rows_to_drop).reset_index(drop=True)

        if len(df_aligned) > 0:
            dataframes.append(df_aligned)

    # --- Final merge ---
    if dataframes:
        consolidated_df = pd.concat(dataframes, ignore_index=True)

        # Define final header format matching the image
        # Order: Manufacturer, Type, heat_output_35_C_in_kw, effeciency_35_C, 
        #        heat_output_55_C_in_kw, effeciency_55_C, Refrigerant, 
        #        grid_service_availability, ee_display_availibility, category
        final_header_map = {
            'Manufacturer': 'Manufacturer',
            'Type': 'Type',
            'Low Temperature Application 35 C': 'heat_output_35_C_in_kw',
            'Low Temperature Application 35 C COP': 'effeciency_35_C',
            'Low Temperature Application 55 C': 'heat_output_55_C_in_kw',
            'Low Temperature Application 55 C COP': 'effeciency_55_C',
            'Refrigerant': 'Refrigerant',
            'Availability': 'grid_service_availability',
            'Availability (2)': 'ee_display_availibility',
            'Category': 'category'
        }
        
        # Rename columns to match the desired format
        consolidated_df = consolidated_df.rename(columns=final_header_map)
        
        # Reorder columns to match image: Manufacturer, Type, heat_output_35_C_in_kw, 
        # effeciency_35_C, heat_output_55_C_in_kw, effeciency_55_C, Refrigerant,
        # grid_service_availability, ee_display_availibility, category
        final_column_order = [
            'Manufacturer', 'Type', 'heat_output_35_C_in_kw', 'effeciency_35_C',
            'heat_output_55_C_in_kw', 'effeciency_55_C', 'Refrigerant',
            'grid_service_availability', 'ee_display_availibility', 'category'
        ]
        consolidated_df = consolidated_df[final_column_order]

        consolidated_df.to_csv(CONSOLIDATED_CSV, index=False, encoding="utf-8")

        print(f"\nConsolidated table saved to: {CONSOLIDATED_CSV}")
        print(f"Total rows: {len(consolidated_df)}")
        print(f"Total columns: {len(consolidated_df.columns)}")
        print(f"Column names: {list(consolidated_df.columns)}")
    else:
        print("No tables could be consolidated!")

Found 441 CSV files to consolidate
Using reference header from table_100.csv
Maximum columns found: 10
Reference header (German): ['Kategorie', 'Hersteller', 'Typ', 'Niedertemperatur- Anwendung 35 °C', 'Niedertemperatur- Anwendung 35 °C.1', 'Niedertemperatur- Anwendung 55 °C', 'Niedertemperatur- Anwendung 55 °C.1', 'Kältemittel', 'Verfügbarkeit (Siehe Hinweis auf Seite 5)', 'Verfügbarkeit (Siehe Hinweis auf Seite 5).1']
Reference header (English): ['Category', 'Manufacturer', 'Type', 'Low Temperature Application 35 C', 'Low Temperature Application 35 C COP', 'Low Temperature Application 55 C', 'Low Temperature Application 55 C COP', 'Refrigerant', 'Availability', 'Availability (2)']


Consolidated table saved to: /mnt/d/heatpump_data/heatpump_table/consolidated_table_1.csv
Total rows: 11994
Total columns: 10
Column names: ['Manufacturer', 'Type', 'heat_output_35_C_in_kw', 'effeciency_35_C', 'heat_output_55_C_in_kw', 'effeciency_55_C', 'Refrigerant', 'grid_service_availability', 'ee_display_availibility', 'category']

In [ ]:
# # Load consolidated CSV and remove category header rows
# consolidated_df = pd.read_csv(CONSOLIDATED_CSV, encoding="utf-8")

# print(f"Original rows: {len(consolidated_df)}")

# # Identify rows that are likely category headers (e.g., "Luft / Wasser", "Abluft / Wasser", etc.)
# # These are rows where most columns are empty and the first column contains category names
# category_patterns = ['Luft / Wasser', 'Luft/Wasser', 'Abluft / Wasser', 'Luft / Luft', 
#                     'Direktverdampfung / Wasser', 'Erdreich / Wasser', 'Sole / Wasser', 'Wasser / Wasser']

# # Second header row pattern: "Wärme- Nennleistung KW", "ETAs 35 %", "ETAs 55 %", "Netzdien- lichkeit", "EE-Anzeige"
# second_header_keywords = ['Wärme- Nennleistung', 'Nennleistung', 'ETAs', 'Netzdien', 'EE-Anzeige', 'KW', '%']

# # Drop rows where:
# # 1. First column contains a category pattern, OR
# # 2. First column is non-empty but most other columns are empty (likely a header row), OR
# # 3. Row contains second header row pattern (Wärme- Nennleistung, ETAs, Netzdien, EE-Anzeige)
# rows_to_drop = []

# for idx, row in consolidated_df.iterrows():
#     first_col = str(row.iloc[0]).strip()
#     row_text = ' '.join([str(x).strip() for x in row.values]).lower()
    
#     # Check if first column matches a category pattern
#     if any(pattern in first_col for pattern in category_patterns):
#         rows_to_drop.append(idx)
#     # Check for second header row pattern
#     elif any(keyword.lower() in row_text for keyword in second_header_keywords):
#         # Count how many second header keywords are present
#         keyword_matches = sum(1 for keyword in second_header_keywords if keyword.lower() in row_text)
#         if keyword_matches >= 3:  # If 3+ keywords found, likely the second header row
#             rows_to_drop.append(idx)
#     # Check if first column is non-empty but most other columns (2-9) are empty
#     elif first_col and first_col != 'nan':
#         non_empty_count = sum(1 for i in range(1, len(row)) if str(row.iloc[i]).strip() and str(row.iloc[i]).strip() != 'nan')
#         if non_empty_count <= 1:  # If only 0-1 other columns have data, likely a header
#             rows_to_drop.append(idx)

# # Drop the identified rows
# consolidated_df_cleaned = consolidated_df.drop(index=rows_to_drop).reset_index(drop=True)

# print(f"Rows dropped: {len(rows_to_drop)}")
# print(f"Remaining rows: {len(consolidated_df_cleaned)}")

# # Save cleaned consolidated CSV
# consolidated_df_cleaned.to_csv(CONSOLIDATED_CSV, index=False, encoding="utf-8")
# print(f"\nCleaned consolidated table saved to: {CONSOLIDATED_CSV}")

Original rows: 11998
Rows dropped: 5
Remaining rows: 11993

Cleaned consolidated table saved to: /mnt/d/heatpump_data/heatpump_table/consolidated_table_1.csv

In [8]:
consolidated_df_cleaned = consolidated_df.copy()

In [9]:
# Display first few rows of consolidated table
consolidated_df_cleaned.head(n = 30)

,Manufacturer,Type,heat_output_35_C_in_kw,effeciency_35_C,heat_output_55_C_in_kw,effeciency_55_C,Refrigerant,grid_service_availability,ee_display_availibility,category
0,AERMEC GmbH,SKG 250 / SKG250W,"2,7","181,0",NaN,,R32,optional,nein,Luft / Luft (Heizleistung <= 12 kW)
1,Bosch Thermotechnik GmbH,CL7000i-Set 20 E - CL7000iU W 20 E / CL7000i 20 E,"2,3","201,0",NaN,,R32,optional,optional,Luft / Luft (Heizleistung <= 12 kW)
2,Bosch Thermotechnik GmbH,CL7000i-Set 26 E - CL7000iU W 26 E / CL7000i 26 E,"4,1","201,0",NaN,,R32,optional,optional,Luft / Luft (Heizleistung <= 12 kW)
3,Bosch Thermotechnik GmbH,CL7000i-Set 26 EB - CL7000iU W 26 EB / CL7000i...,"4,1","201,0",NaN,,R32,optional,optional,Luft / Luft (Heizleistung <= 12 kW)
4,Bosch Thermotechnik GmbH,CL7000i-Set 26 ES - CL7000iU W 26 ES / CL7000i...,"4,1","201,0",NaN,,R32,optional,optional,Luft / Luft (Heizleistung <= 12 kW)
5,Bosch Thermotechnik GmbH,CL7000i-Set 35 E - CL7000iU W 35 E / CL7000i 35 E,"4,1","201,0",NaN,,R32,optional,optional,Luft / Luft (Heizleistung <= 12 kW)
6,Bosch Thermotechnik GmbH,CL7000i-Set 35 EB - CL7000iU W 35 EB / CL7000i...,"4,1","201,0",NaN,,R32,optional,optional,Luft / Luft (Heizleistung <= 12 kW)
7,Bosch Thermotechnik GmbH,CL7000i-Set 35 ES - CL7000iU W 35 ES / CL7000i...,"4,1","201,0",NaN,,R32,optional,optional,Luft / Luft (Heizleistung <= 12 kW)
8,Bosch Thermotechnik GmbH,CL7000i-Set 53 E - CL7000iU W 53 E / CL7000i 53 E,"5,6","181,0",NaN,,R32,optional,optional,Luft / Luft (Heizleistung <= 12 kW)
9,Bosch Thermotechnik GmbH,CL7000M 53/2 E,"5,3","181,0",NaN,,R32,optional,optional,Luft / Luft (Heizleistung <= 12 kW)
10,Bosch Thermotechnik GmbH,CL7000M 79/3 E,"7,9","181,0",NaN,,R32,optional,optional,Luft / Luft (Heizleistung <= 12 kW)
11,Buderus - Bosch Thermotechnik GmbH,"AC186i.3-Set 2,6 W - AC186i.3-2,6 W / AC186i. ...","4,1","201,0",NaN,,R32,optional,optional,Luft / Luft (Heizleistung <= 12 kW)
12,Buderus - Bosch Thermotechnik GmbH,"AC186i.3-Set 2,6 W S - AC186i.3-2,6 W S / AC18...","4,1","201,0",NaN,,R32,optional,optional,Luft / Luft (Heizleistung <= 12 kW)
13,Buderus - Bosch Thermotechnik GmbH,"AC186i.3-Set 3,5 W - AC186i.3-3,5 W / AC186i. ...","4,1","201,0",NaN,,R32,optional,optional,Luft / Luft (Heizleistung <= 12 kW)
14,Buderus - Bosch Thermotechnik GmbH,"AC186i.3-Set 3,5 W S - AC186i.3-3,5 W S / AC18...","4,1","201,0",NaN,,R32,optional,optional,Luft / Luft (Heizleistung <= 12 kW)
15,Buderus - Bosch Thermotechnik GmbH,"AC186i.3-Set 5,3 W - AC186i.3-5,3 W / AC186i. ...","5,6","181,0",NaN,,R32,optional,optional,Luft / Luft (Heizleistung <= 12 kW)
16,Buderus - Bosch Thermotechnik GmbH,"AC186i.3-Set 5,3 W S - AC186i.3-5,3 W S / AC18...","5,6","181,0",NaN,,R32,optional,optional,Luft / Luft (Heizleistung <= 12 kW)
17,Buderus - Bosch Thermotechnik GmbH,"AC-5,3 MS E+","5,3","181,0",NaN,,R32,optional,optional,Luft / Luft (Heizleistung <= 12 kW)
18,Buderus - Bosch Thermotechnik GmbH,"AC-7,9 MS E+","7,9","181,0",NaN,,R32,optional,optional,Luft / Luft (Heizleistung <= 12 kW)
19,"Carrier Air Conditioning Co., LTD",38WHSH020A1A0TEE,"2,5","201,0",NaN,,R32,optional,ja,Luft / Luft (Heizleistung <= 12 kW)
20,Clivet,WiSAN-P 20.1 LN,"48,2","163,0","43,7","131,0",R290,ja,ja,Luft / Wasser
21,Clivet,WiSAN-P 20.1 SC,"48,2","163,0","43,7","131,0",R290,ja,ja,Luft / Wasser
22,Clivet,WiSAN-P 25.2 EN,"52,5","185,0","49,6","142,0",R290,ja,ja,Luft / Wasser
23,Clivet,WiSAN-P 25.2 LN,"52,5","185,0","49,6","142,0",R290,ja,ja,Luft / Wasser
24,Clivet,WiSAN-P 25.2 SC,"52,5","185,0","49,6","142,0",R290,ja,ja,Luft / Wasser
25,Clivet,WiSAN-P 30.2 EN,"61,3","179,0","55,1","141,0",R290,ja,ja,Luft / Wasser
26,Clivet,WiSAN-P 30.2 LN,"61,3","179,0","55,1","141,0",R290,ja,ja,Luft / Wasser
27,Clivet,WiSAN-P 30.2 SC,"61,3","179,0","55,1","141,0",R290,ja,ja,Luft / Wasser
28,Clivet,WiSAN-YEE1 45.4 EN,"92,0","163,0",NaN,NaN,R32,optional,ja,Luft / Wasser
29,Clivet,WiSAN-YEE1 45.4 LN,"92,0","163,0",NaN,NaN,R32,optional,ja,Luft / Wasser

In [32]:
# Display basic info about the consolidated table
consolidated_df_cleaned.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11995 entries, 0 to 11994
Data columns (total 10 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   Category                              11995 non-null  object
 1   Manufacturer                          11995 non-null  object
 2   Type                                  11995 non-null  object
 3   Low Temperature Application 35 C      11753 non-null  object
 4   Low Temperature Application 35 C COP  11807 non-null  object
 5   Low Temperature Application 55 C      8911 non-null   object
 6   Low Temperature Application 55 C COP  11110 non-null  object
 7   Refrigerant                           11846 non-null  object
 8   Availability                          11993 non-null  object
 9   Availability (2)                      11993 non-null  object
dtypes: object(10)
memory usage: 937.2+ KB

In [33]:
df = consolidated_df_cleaned.copy()

In [34]:
df.head(n = 30)

,Category,Manufacturer,Type,Low Temperature Application 35 C,Low Temperature Application 35 C COP,Low Temperature Application 55 C,Low Temperature Application 55 C COP,Refrigerant,Availability,Availability (2)
0,,,,Heat Output KW,Efficiency 35 %,Heat Output KW,Efficiency 55 %,,Grid Service,EE Display
1,Luft / Luft (Heizleistung <= 12 kW),AERMEC GmbH,SKG 250 / SKG250W,"2,7","181,0",NaN,R32,optional,nein,
2,Luft / Luft (Heizleistung <= 12 kW),Bosch Thermotechnik GmbH,CL7000i-Set 20 E - CL7000iU W 20 E / CL7000i 20 E,"2,3","201,0",NaN,R32,optional,optional,
3,Luft / Luft (Heizleistung <= 12 kW),Bosch Thermotechnik GmbH,CL7000i-Set 26 E - CL7000iU W 26 E / CL7000i 26 E,"4,1","201,0",NaN,R32,optional,optional,
4,Luft / Luft (Heizleistung <= 12 kW),Bosch Thermotechnik GmbH,CL7000i-Set 26 EB - CL7000iU W 26 EB / CL7000i...,"4,1","201,0",NaN,R32,optional,optional,
5,Luft / Luft (Heizleistung <= 12 kW),Bosch Thermotechnik GmbH,CL7000i-Set 26 ES - CL7000iU W 26 ES / CL7000i...,"4,1","201,0",NaN,R32,optional,optional,
6,Luft / Luft (Heizleistung <= 12 kW),Bosch Thermotechnik GmbH,CL7000i-Set 35 E - CL7000iU W 35 E / CL7000i 35 E,"4,1","201,0",NaN,R32,optional,optional,
7,Luft / Luft (Heizleistung <= 12 kW),Bosch Thermotechnik GmbH,CL7000i-Set 35 EB - CL7000iU W 35 EB / CL7000i...,"4,1","201,0",NaN,R32,optional,optional,
8,Luft / Luft (Heizleistung <= 12 kW),Bosch Thermotechnik GmbH,CL7000i-Set 35 ES - CL7000iU W 35 ES / CL7000i...,"4,1","201,0",NaN,R32,optional,optional,
9,Luft / Luft (Heizleistung <= 12 kW),Bosch Thermotechnik GmbH,CL7000i-Set 53 E - CL7000iU W 53 E / CL7000i 53 E,"5,6","181,0",NaN,R32,optional,optional,
10,Luft / Luft (Heizleistung <= 12 kW),Bosch Thermotechnik GmbH,CL7000M 53/2 E,"5,3","181,0",NaN,R32,optional,optional,
11,Luft / Luft (Heizleistung <= 12 kW),Bosch Thermotechnik GmbH,CL7000M 79/3 E,"7,9","181,0",NaN,R32,optional,optional,
12,Luft / Luft (Heizleistung <= 12 kW),Buderus - Bosch Thermotechnik GmbH,"AC186i.3-Set 2,6 W - AC186i.3-2,6 W / AC186i. ...","4,1","201,0",NaN,R32,optional,optional,
13,Luft / Luft (Heizleistung <= 12 kW),Buderus - Bosch Thermotechnik GmbH,"AC186i.3-Set 2,6 W S - AC186i.3-2,6 W S / AC18...","4,1","201,0",NaN,R32,optional,optional,
14,Luft / Luft (Heizleistung <= 12 kW),Buderus - Bosch Thermotechnik GmbH,"AC186i.3-Set 3,5 W - AC186i.3-3,5 W / AC186i. ...","4,1","201,0",NaN,R32,optional,optional,
15,Luft / Luft (Heizleistung <= 12 kW),Buderus - Bosch Thermotechnik GmbH,"AC186i.3-Set 3,5 W S - AC186i.3-3,5 W S / AC18...","4,1","201,0",NaN,R32,optional,optional,
16,Luft / Luft (Heizleistung <= 12 kW),Buderus - Bosch Thermotechnik GmbH,"AC186i.3-Set 5,3 W - AC186i.3-5,3 W / AC186i. ...","5,6","181,0",NaN,R32,optional,optional,
17,Luft / Luft (Heizleistung <= 12 kW),Buderus - Bosch Thermotechnik GmbH,"AC186i.3-Set 5,3 W S - AC186i.3-5,3 W S / AC18...","5,6","181,0",NaN,R32,optional,optional,
18,Luft / Luft (Heizleistung <= 12 kW),Buderus - Bosch Thermotechnik GmbH,"AC-5,3 MS E+","5,3","181,0",NaN,R32,optional,optional,
19,Luft / Luft (Heizleistung <= 12 kW),Buderus - Bosch Thermotechnik GmbH,"AC-7,9 MS E+","7,9","181,0",NaN,R32,optional,optional,
20,Luft / Luft (Heizleistung <= 12 kW),"Carrier Air Conditioning Co., LTD",38WHSH020A1A0TEE,"2,5","201,0",NaN,R32,optional,ja,
21,Luft / Wasser,Clivet,WiSAN-P 20.1 LN,"48,2","163,0","43,7","131,0",R290,ja,ja
22,Luft / Wasser,Clivet,WiSAN-P 20.1 SC,"48,2","163,0","43,7","131,0",R290,ja,ja
23,Luft / Wasser,Clivet,WiSAN-P 25.2 EN,"52,5","185,0","49,6","142,0",R290,ja,ja
24,Luft / Wasser,Clivet,WiSAN-P 25.2 LN,"52,5","185,0","49,6","142,0",R290,ja,ja
25,Luft / Wasser,Clivet,WiSAN-P 25.2 SC,"52,5","185,0","49,6","142,0",R290,ja,ja
26,Luft / Wasser,Clivet,WiSAN-P 30.2 EN,"61,3","179,0","55,1","141,0",R290,ja,ja
27,Luft / Wasser,Clivet,WiSAN-P 30.2 LN,"61,3","179,0","55,1","141,0",R290,ja,ja
28,Luft / Wasser,Clivet,WiSAN-P 30.2 SC,"61,3","179,0","55,1","141,0",R290,ja,ja
29,Luft / Wasser,Clivet,WiSAN-YEE1 45.4 EN,"92,0","163,0",NaN,NaN,R32,optional,ja

In [ ]:
# # --- Add Kategorie column based on section rows ---
# import pandas as pd

# def is_section_row(row):
#     non_empty = [str(c).strip() for c in row if pd.notna(c) and str(c).strip() != ""]
#     return len(non_empty) == 1

# current_category = None
# records = []

# for _, row in df.iterrows():
#     values = [str(c).strip() if pd.notna(c) else "" for c in row]

#     if is_section_row(values):
#         current_category = values[0]
#         continue

#     if not values[0]:
#         continue

#     record = {"Kategorie": current_category}
#     record.update(dict(zip(df.columns, values)))
#     records.append(record)

# df = pd.DataFrame(records)

# # Optional sanity check
# assert df['Category'].notna().all()

# df.to_csv("consolidated_table_with_category.csv", index=False)

KeyError: 'Kategorie'

In [40]:
!uv pip install openpyxl

Using Python 3.11.14 environment at: /home/abhishek/Documents/heatpump_ai_2/climate_data_prep/.venv
Resolved 2 packages in 149ms
Installed 2 packages in 52ms
 + et-xmlfile==2.0.0
 + openpyxl==3.1.5

In [45]:
import pandas as pd

df1 = pd.read_csv(CONSOLIDATED_CSV)

# df1 = pd.read_csv("consolidated_table_1.csv")

# Drop first row and reset index
df1 = df1.iloc[1:].reset_index(drop=True)
df2 = pd.read_excel("/mnt/c/Users/Abhishek/Downloads/head_load.xlsx")

# Example column alignment (adjust as needed)

rename_map = {
    "Manufacturer": "manufacturer",
    "Type": "model_type",
    "Low Temperature Application 35 C": "heat_output_35_kw",
    "Low Temperature Application 35 C COP": "cop_35",
    "Low Temperature Application 55 C": "heat_output_55_kw",
    "Low Temperature Application 55 C COP": "cop_55",
    "Category": "category",
    "Refrigerant": "refrigerant",
    "Availability": "grid_service_availability",
    "Availability (2)": "ee_display_availability"
}

df1 = df1.rename(columns=rename_map)


# Sort and reset index
df1 = df1.sort_values(list(df1.columns)).reset_index(drop=True)
df2 = df2.sort_values(list(df2.columns)).reset_index(drop=True)

# Exact comparison
df1.equals(df2)

False

In [49]:
df1.head()

,manufacturer,model_type,heat_output_35_kw,cop_35,heat_output_55_kw,cop_55,refrigerant,grid_service_availability,ee_display_availability,category
0,1A HEIZEN STROBL UG,1A COP TOP 14R,"14,0","161,2","8,8","125,0",R32,ja,ja,Direktkondensation im Pufferspeicher (Sonderba...
1,1SINQ GmbH,1SINQ ONE-10,"10,2","220,0","10,0","165,0",R290,ja,ja,Luft / Wasser
2,1SINQ GmbH,1SINQ ONE-14E,"15,4","194,0","14,2","152,0",R290,ja,ja,Luft / Wasser
3,1SINQ GmbH,1SINQ ONE-16,"15,5","217,0","16,0","158,0",R290,ja,ja,Luft / Wasser
4,1SINQ GmbH,1SINQ ONE-18,"18,8","200,0","18,0","158,0",R290,ja,ja,Luft / Wasser

In [51]:
df2.head()

,manufacturer,model_type,heat_output_35_kw,cop_35,heat_output_55_kw,cop_55,refrigerant,grid_service_availability,ee_display_availability,category
0,1A HEIZEN STROBL UG,1A COP TOP 14R,"14,0","161,2","8,8","125,0",R32,ja,ja,Direktkondensation im Pufferspeicher (Sonderba...
1,1SINQ GmbH,1SINQ ONE-10,"10,2","220,0","10,0","165,0",R290,ja,ja,Luft / Wasser
2,1SINQ GmbH,1SINQ ONE-14E,"15,4","194,0","14,2","152,0",R290,ja,ja,Luft / Wasser
3,1SINQ GmbH,1SINQ ONE-16,"15,5","217,0","16,0","158,0",R290,ja,ja,Luft / Wasser
4,1SINQ GmbH,1SINQ ONE-18,"18,8","200,0","18,0","158,0",R290,ja,ja,Luft / Wasser

In [52]:
df1 = df1.reset_index(drop=True)
df2 = df2.reset_index(drop=True)
diff = df1.compare(df2)
diff.head()

ValueError: Can only compare identically-labeled (both index and columns) DataFrame objects

In [53]:
# 1. Ensure same column order
df1 = df1[df2.columns]

# 2. Sort deterministically
sort_cols = list(df1.columns)
df1 = df1.sort_values(sort_cols)
df2 = df2.sort_values(sort_cols)

# 3. Reset index (CRITICAL)
df1 = df1.reset_index(drop=True)
df2 = df2.reset_index(drop=True)

# 4. Compare
df1.equals(df2)      # True / False
diff = df1.compare(df2)

ValueError: Can only compare identically-labeled (both index and columns) DataFrame objects