# Extract U-Values from Tabula.xlsm

This notebook extracts all columns for Germany (DE) from the "Tab.Building.Constr" sheet in the Tabula.xlsm file.

In [1]:
%pip install pandas openpyxl

Using Python 3.11.14 environment at: /home/abhishek/Documents/heatpump_ai_2/.venv
Resolved 8 packages in 289ms
⠙ Preparing packages... (0/2)
⠙ Preparing packages... (0/2)-------------------     0 B/17.64 KiB
⠙ Preparing packages... (0/2)---------- 16.00 KiB/17.64 KiB
⠙ Preparing packages... (0/2)---------- 16.00 KiB/17.64 KiB
et-xmlfile           ------------------------------ 16.00 KiB/17.64 KiB
⠙ Preparing packages... (0/2)-------------------     0 B/245.03 KiB
et-xmlfile           ------------------------------ 17.64 KiB/17.64 KiB
⠙ Preparing packages... (0/2)-------------------     0 B/245.03 KiB
et-xmlfile           ------------------------------ 17.64 KiB/17.64 KiB
⠙ Preparing packages... (0/2)-------------------     0 B/245.03 KiB
⠙ Preparing packages... (0/2)-------------------     0 B/245.03 KiB
⠙ Preparing packages... (0/2)------------------- 16.00 KiB/245.03 KiB
⠙ Preparing packages... (0/2)------------------- 32.00 KiB/245.03 KiB
⠙ Preparing packages... (0/2)------------------- 48.00 KiB/245.03 KiB
⠙ Preparing packages... (0/2)------------------- 62.35 KiB/245.03 KiB
⠙ Preparing packages... (0/2)------------------- 78.35 KiB/245.03 KiB
⠙ Preparing packages... (0/2)------------------- 94.35 KiB/245.03 KiB
⠙ Preparing packages... (0/2)2m----------------- 110.35 KiB/245.03 KiB
⠙ Preparing packages... (0/2)--------------- 126.35 KiB/245.03 KiB
⠙ Preparing packages... (0/2)0m------------- 142.35 KiB/245.03 KiB
⠙ Preparing packages... (0/2)[30m----------- 158.35 KiB/245.03 KiB
⠙ Preparing packages... (0/2)---------- 174.35 KiB/245.03 KiB
Prepared 2 packages in 72ms
Installed 2 packages in 11ms
 + et-xmlfile==2.0.0
 + openpyxl==3.1.5

In [2]:
import pandas as pd
import os
from pathlib import Path

In [4]:
# Path to the Excel file
excel_path = "/mnt/d/heatpump_data/TABULA_xlsm_Download/Tabula.xlsm"
sheet_name = "Tab.Building.Constr"

# Verify file exists
if not os.path.exists(excel_path):
    raise FileNotFoundError(f"Excel file not found at: {excel_path}")

print(f"Reading Excel file: {excel_path}")
print(f"Target sheet: {sheet_name}")

Reading Excel file: /mnt/d/heatpump_data/TABULA-xlsm_Download/Tabula.xlsm
Target sheet: Tab.Building.Constr

In [5]:
# Load the Excel file and list all sheet names
xl_file = pd.ExcelFile(excel_path, engine='openpyxl')
print("Available sheets:")
for idx, sheet in enumerate(xl_file.sheet_names, 1):
    print(f"  {idx}. {sheet}")
    
# Verify the target sheet exists
if sheet_name not in xl_file.sheet_names:
    raise ValueError(f"Sheet '{sheet_name}' not found in the Excel file!")

Available sheets:
  1. Info
  2. Tab.Info.Country
  3. Definitions
  4. Log.Changes
  5. Dev.Tasks
  6. Settings
  7. BlankSheet
  8. Tab.Control.Sheet
  9. Dev.Tab.TEST
  10. Tab.Const.DataFormat
  11. Tab.Const.StatusDataset
  12. Tab.Const.TypeVariant
  13. Tab.Const.TypeIntake
  14. Tab.Const.DataType.Building
  15. Tab.Const.Country
  16. Tab.Const.Language
  17. Tab.Const.BuildingSizeClass
  18. Tab.Const.BoundaryCondType
  19. Tab.Const.Utilisation
  20. Tab.Const.RoofType
  21. Tab.Const.AtticCond
  22. Tab.Const.CellarCond
  23. Tab.Const.AttNeighb
  24. Tab.Const.ComplexFootprint
  25. Tab.Const.ComplexRoof
  26. Tab.Const.Orientation
  27. Tab.Const.ConstrBorder
  28. Tab.Const.ThermalBridging
  29. Tab.Const.Infiltration
  30. Tab.Const.ElementType
  31. Tab.Const.MeasureType
  32. Tab.Const.EnergyCarrier
  33. Tab.Const.SysType.Size
  34. Tab.Const.SysType.HG
  35. Tab.Const.SysType.HS
  36. Tab.Const.SysType.HD
  37. Tab.Const.SysType.HA
  38. Tab.Const.SysType.WG
  39. Tab.Const.SysType.WS
  40. Tab.Const.SysType.WD
  41. Tab.Const.SysType.WA
  42. Tab.Const.SysType.Vent
  43. Tab.Const.Type.CalcAdapt
  44. Tab.TypologyRegion
  45. Tab.ConstrYearClass
  46. Tab.AdditionalPar
  47. Tab.Climate
  48. Tab.BoundaryCond
  49. Tab.AuxCalc.Climate
  50. Tab.Par.EnvAreaEstim
  51. Tab.Building.Constr
  52. Tab.Building.Measure
  53. Tab.U.Class.Constr
  54. Tab.U.Class.Window
  55. Tab.System.HG
  56. Tab.System.HS
  57. Tab.System.HD
  58. Tab.System.HA
  59. Tab.System.WG
  60. Tab.System.WS
  61. Tab.System.WD
  62. Tab.System.WA
  63. Tab.System.H
  64. Tab.System.W
  65. Tab.System.Vent
  66. Tab.System.PVPanel
  67. Tab.System.PV
  68. Tab.System.Coverage
  69. Tab.System.ElProd
  70. Tab.System.SetECAssess
  71. Tab.System.EC
  72. Tab.CalcAdapt
  73. Tab.Type.Building
  74. Tab.Type.System
  75. Tab.System.Measure
  76. Data.In.EnergyProfile
  77. Tab.Building
  78. Calc.Building.Set
  79. Calc.System.Set
  80. Output.Overview.Flex
  81. Output.Overview.Variants
  82. Calculator.Set.Building
  83. Calculator.Set.System
  84. Output.Set.1
  85. Output.Set.2
  86. Output.Set.3
  87. Output.Calculator.Building
  88. Calc.Demo.EnvAreaEstim
  89. UserForm
  90. Calc.Demo.Refurbish
  91. Calc.Demo.Building
  92. Calc.Demo.System
  93. Calc.Demo.Charts
  94. Calc.Demo.Charts OLD version
  95. Calculator.Set.BuildingStock
  96. Tab.BuildingStock
  97. Calc.AverageBuiSys.Set
  98. Calc.Demo.AverageBuiSys
  99. Calc.Economy.Set
  100. Calc.Demo.Selection
  101. List.Selection

In [6]:
# Read the target sheet
df = pd.read_excel(excel_path, sheet_name=sheet_name, engine='openpyxl')

print(f"Shape of the data: {df.shape}")
print(f"\nColumn names:")
print(df.columns.tolist())
print(f"\nFirst few rows:")
df.head()

Shape of the data: (2466, 35)

Column names:
['Code_Construction', 'Code_StatusDataset', 'Code_Country', 'Code_ElementType', 'Code_DataType_Construction', 'Code_Construction_ConstructionYearClass', 'Number_Construction_Variant', 'Type_Construction', 'Type_Construction_National', 'Description_Construction', 'Description_Construction_National', 'Remark_Construction', 'Name_Picture_Construction', 'Picture_Construction', 'Year1_Construction', 'Year2_Construction', 'd_Insulation', 'U', 'g_gl_n', 'Indicator_Constr_Massive', 'Indicator_Constr_Wood', 'Indicator_Window_FrameMaterial', 'Indicator_Window_FrameInsulation', 'Indicator_Window_NumberPanes', 'Indicator_Window_LowE', 'Indicator_Window_GasFilling', 'Date_Entry', 'Date_Change', 'Note_DataBaseAdmin', 'Unnamed: 29', 'Unnamed: 30', 'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34']

First few rows:

,Code_Construction,Code_StatusDataset,Code_Country,Code_ElementType,Code_DataType_Construction,Code_Construction_ConstructionYearClass,Number_Construction_Variant,Type_Construction,Type_Construction_National,Description_Construction,...,Indicator_Window_GasFilling,Date_Entry,Date_Change,Note_DataBaseAdmin,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32,Unnamed: 33,Unnamed: 34
0,dataset identification,code of the dataset status,ISO 3166-1-alpha-2 code,code of the thermal envelope element type,code of the building data type,code of the construction year class,variant number of construction,short characterisation of the construction type,short characterisation of the construction typ...,detailed description,...,gas filling between window panes,date of entry into database,date of last change,note or advice by database administration,NaN,Plausibility Control of U-values (insulated co...,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,if a construction is used during several const...,index of the construction in the given constru...,NaN,NaN,NaN,...,"possible entries: """", ""inert gas"", ""Argon"", ""K...",NaN,NaN,implemented / necessary / recommended changes,NaN,lamda,wood fraction,fraction of insulation thickness with continuo...,R_other,U-value
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,W/(m·K),NaN,m,m²K/W,W/(m²K)
3,NaN,Tab.Const.StatusDataset,Tab.Const.Country,Tab.Const.ElementType,Tab.Const.DataType.Building,Tab.ConstrYearClass,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,VarChar,VarChar,VarChar,VarChar,VarChar,VarChar,Integer,VarChar,VarChar,Text,...,VarChar,Date,Date,Text,NaN,NaN,NaN,NaN,NaN,NaN

First column name: 'Code_Construction'

Sample values from first column:
0     dataset identification
1                        NaN
2                        NaN
3                        NaN
4                    VarChar
5                        NaN
6                        NaN
7                        NaN
8                        NaN
9         ##.Roof.ReEx.01.01
10     DE.Ceiling.ReEx.01.01
11     DE.Ceiling.ReEx.03.01
12     DE.Ceiling.ReEx.04.01
13     DE.Ceiling.ReEx.04.02
14     DE.Ceiling.ReEx.06.01
15     DE.Ceiling.ReEx.07.01
16     DE.Ceiling.ReEx.07.02
17     DE.Ceiling.ReEx.08.01
18     DE.Ceiling.ReEx.08.02
19     DE.Ceiling.ReEx.09.01
Name: Code_Construction, dtype: object

Unique country codes found (extracting prefix before first dot):
Country codes: ['AT', 'BA', 'BE', 'BG', 'CY', 'CZ', 'DE', 'DK', 'ES', 'FR', 'GB', 'GR', 'HU', 'IE', 'IT', 'NL', 'NO', 'PL', 'RS', 'SE', 'SI', 'XX']

Count of rows starting with 'DE.':
  Rows starting with 'DE.': 155
  Total rows: 2466

In [ ]:
# Check for country code column (likely named something like 'Country', 'Country Code', 'ISO', 'DE', etc.)
print("Checking for country-related columns:")
country_cols = [col for col in df.columns if any(keyword in str(col).lower() for keyword in ['country', 'iso', 'code', 'nation'])]
print(f"Potential country columns: {country_cols}")

# Display unique values in potential country columns
for col in country_cols[:3]:  # Check first 3 potential columns
    print(f"\nUnique values in '{col}':")
    print(df[col].unique()[:20])  # Show first 20 unique values

Checking for country-related columns:
Potential country columns: ['Code_Construction', 'Code_StatusDataset', 'Code_Country', 'Code_ElementType', 'Code_DataType_Construction', 'Code_Construction_ConstructionYearClass', 'Type_Construction_National', 'Description_Construction_National']

Unique values in 'Code_Construction':
['dataset identification' nan 'VarChar' '##.Roof.ReEx.01.01'
 'DE.Ceiling.ReEx.01.01' 'DE.Ceiling.ReEx.03.01' 'DE.Ceiling.ReEx.04.01'
 'DE.Ceiling.ReEx.04.02' 'DE.Ceiling.ReEx.06.01' 'DE.Ceiling.ReEx.07.01'
 'DE.Ceiling.ReEx.07.02' 'DE.Ceiling.ReEx.08.01' 'DE.Ceiling.ReEx.08.02'
 'DE.Ceiling.ReEx.09.01' 'DE.Ceiling.ReEx.09.02' 'DE.Ceiling.ReEx.10.01'
 'DE.Ceiling.ReEx.10.02' 'DE.Ceiling.ReEx.11.01' 'DE.Ceiling.ReEx.11.02'
 'DE.Door.ReEx.01.01']

Unique values in 'Code_StatusDataset':
['code of the dataset status' nan 'Tab.Const.StatusDataset' 'VarChar'
 'Template' 'Typology' 'Demonstration']

Unique values in 'Code_Country':
['ISO 3166-1-alpha-2 code' nan 'Tab.Const.Country' 'VarChar' '##' 'DE'
 'PL' 'XX' 'SE' 'BG' 'RS' 'IT' 'GB' 'CY' 'IE' 'SI' 'CZ' 'AT' 'HU' 'BE']

In [ ]:
# Filter for Germany (DE) - adjust column name and value based on actual data structure
# Common patterns: 'DE', 'Germany', 'GER', etc.

# Try to find the country column automatically
country_column = None
for col in df.columns:
    unique_vals = df[col].dropna().astype(str).unique()
    if any(val.upper() in ['DE', 'GERMANY', 'GER'] for val in unique_vals):
        country_column = col
        print(f"Found country column: '{col}'")
        print(f"Unique values: {df[col].dropna().unique()[:10]}")
        break

if country_column is None:
    print("Could not automatically detect country column. Please inspect the data above.")
    print("You may need to manually specify the country column name.")
else:
    # Filter for DE/Germany
    de_mask = df[country_column].astype(str).str.upper().isin(['DE', 'GERMANY', 'GER'])
    df_de = df[de_mask].copy()
    
    print(f"\nFiltered data for Germany:")
    print(f"  Original rows: {len(df)}")
    print(f"  Germany rows: {len(df_de)}")
    print(f"  Columns: {len(df_de.columns)}")

Filtered data for Germany:
  Original rows: 2466
  Germany rows: 155
  Columns: 35

Sample of filtered Code_Construction values:
['DE.Ceiling.ReEx.01.01', 'DE.Ceiling.ReEx.03.01', 'DE.Ceiling.ReEx.04.01', 'DE.Ceiling.ReEx.04.02', 'DE.Ceiling.ReEx.06.01', 'DE.Ceiling.ReEx.07.01', 'DE.Ceiling.ReEx.07.02', 'DE.Ceiling.ReEx.08.01', 'DE.Ceiling.ReEx.08.02', 'DE.Ceiling.ReEx.09.01']

In [ ]:
# Display the filtered data
if 'df_de' in locals():
    print("Sample of Germany data:")
    df_de.head(10)
else:
    print("Please run the previous cell first to filter the data.")

Sample of Germany data:
DataFrame shape: (155, 35)

        Code_Construction Code_StatusDataset Code_Country Code_ElementType  \
10  DE.Ceiling.ReEx.01.01           Typology           DE          Ceiling
11  DE.Ceiling.ReEx.03.01           Typology           DE          Ceiling
12  DE.Ceiling.ReEx.04.01           Typology           DE          Ceiling
13  DE.Ceiling.ReEx.04.02           Typology           DE          Ceiling
14  DE.Ceiling.ReEx.06.01           Typology           DE          Ceiling
15  DE.Ceiling.ReEx.07.01           Typology           DE          Ceiling
16  DE.Ceiling.ReEx.07.02           Typology           DE          Ceiling
17  DE.Ceiling.ReEx.08.01           Typology           DE          Ceiling
18  DE.Ceiling.ReEx.08.02           Typology           DE          Ceiling
19  DE.Ceiling.ReEx.09.01           Typology           DE          Ceiling

   Code_DataType_Construction Code_Construction_ConstructionYearClass  \
10                       ReEx                                   DE.01
11                       ReEx                                   DE.03
12                       ReEx                                   DE.04
13                       ReEx                                   DE.04
14                       ReEx                                   DE.06
15                       ReEx                                   DE.07
16                       ReEx                                   DE.07
17                       ReEx                                   DE.08
18                       ReEx                                   DE.08
19                       ReEx                                   DE.09

   Number_Construction_Variant                          Type_Construction  \
10                           1     wooden beam ceiling with visible beams
11                           1                        wooden beam ceiling
12                           1                      cavity blocks ceiling
13                           2                           concrete ceiling
14                           1      concrete ceiling with 5 cm insulation
15                           1      concrete ceiling with 6 cm insulation
16                           2  wooden beam ceiling with 10 cm insulation
17                           1     concrete ceiling with 10 cm insulation
18                           2  wooden beam ceiling with 16 cm insulation
19                           1     concrete ceiling with 10 cm insulation

                         Type_Construction_National  \
10            Holzbalkendecke mit sichtbaren Balken
11                                  Holzbalkendecke
12  Rippendecke, Stahlsteindecke, Gitterträgerdecke
13                                       Betondecke
14                      Betondecke mit 5 cm Dämmung
15                      Betondecke mit 6 cm Dämmung
16                Holzbalkendecke mit 10 cm Dämmung
17                     Betondecke mit 10 cm Dämmung
18                Holzbalkendecke mit 16 cm Dämmung
19                     Betondecke mit 10 cm Dämmung

                             Description_Construction  ...  \
10        wooden beams, cavity filled with clay/straw  ...
11  wooden beams, cavity filled with clay, sand or...  ...
12  cavity elements, reinforcement, concrete filli...  ...
13  reinforced concrete, 1 cm insulation, cement s...  ...
14  reinforced concrete, 5 cm insulation, cement s...  ...
15  reinforced concrete, 6 cm insulation, cement s...  ...
16       wooden beams, 10 cm insulation in the cavity  ...
17  reinforced concrete, 10 cm insulation, cement ...  ...
18       wooden beams, 16 cm insulation in the cavity  ...
19  reinforced concrete, 10 cm insulation, cement ...  ...

   Indicator_Window_GasFilling           Date_Entry Date_Change  \
10                         NaN  2010-09-07 00:00:00         NaN
11                         NaN  2010-09-07 00:00:00         NaN
12                         NaN  2010-09-07 00:00:00         NaN
13                         NaN  2010-09-07 00:00:00         NaN
14                         NaN  2010-09-07 00:00:00         NaN
15                         NaN  2010-09-07 00:00:00         NaN
16                         NaN  2010-09-07 00:00:00         NaN
17                         NaN  2010-09-07 00:00:00         NaN
18                         NaN  2010-09-07 00:00:00         NaN
19                         NaN  2010-09-07 00:00:00         NaN

   Note_DataBaseAdmin Unnamed: 29 Unnamed: 30 Unnamed: 31 Unnamed: 32  \
10                NaN         NaN         NaN         NaN         NaN
11                NaN         NaN         NaN         NaN         NaN
12                NaN         NaN         NaN         NaN         NaN
13                NaN         NaN        0.04         NaN         NaN
14                NaN         NaN        0.04         NaN         NaN
15                NaN         NaN        0.04         NaN         NaN
16                NaN         NaN        0.04        0.15         NaN
17                NaN         NaN        0.04         NaN         NaN
18                NaN         NaN        0.04        0.15         NaN
19                NaN         NaN        0.04         NaN         NaN

   Unnamed: 33 Unnamed: 34
10         NaN         NaN
11         NaN         NaN
12         NaN         NaN
13         NaN    2.380952
14         NaN    0.704225
15         NaN    0.598802
16         NaN    0.478057
17         NaN    0.374532
18         NaN    0.310921
19         NaN    0.374532

[10 rows x 35 columns]

In [ ]:
# Save the extracted data
if 'df_de' in locals():
    output_dir = Path("output")
    output_dir.mkdir(exist_ok=True)
    
    # Save as CSV
    csv_path = output_dir / "germany_u_values.csv"
    df_de.to_csv(csv_path, index=False)
    print(f"Saved CSV to: {csv_path}")
    
    # Save as Excel
    excel_output_path = output_dir / "germany_u_values.xlsx"
    df_de.to_excel(excel_output_path, index=False, engine='openpyxl')
    print(f"Saved Excel to: {excel_output_path}")
    
    print(f"\nSummary:")
    print(f"  Total rows: {len(df_de)}")
    print(f"  Total columns: {len(df_de.columns)}")
else:
    print("No data to save. Please run the filtering cell first.")

Saved CSV to: /mnt/d/heatpump_data/u_values/germany_u_values.csv

Summary:
  Total rows: 155
  Total columns: 35

In [ ]:
# Display column information
if 'df_de' in locals():
    print("All columns in Germany dataset:")
    for idx, col in enumerate(df_de.columns, 1):
        non_null_count = df_de[col].notna().sum()
        print(f"{idx:3d}. {col:50s} - Non-null values: {non_null_count}/{len(df_de)}")

Shape of the data: (169, 13)

Column names:
['Code_ConstructionYearClass', 'Code_StatusDataset', 'Code_Country', 'Number_ConstructionYearClass', 'Description_ConstructionYearClass', 'Description_ConstructionYearClass_National', 'Remark_ConstructionYearClass', 'ConstructionYearClass_FirstYear', 'ConstructionYearClass_LastYear', 'Code_ConstructionYearClass_National', 'Date_Entry', 'Date_Change', 'Note_DataBaseAdmin']

First few rows:

,Code_ConstructionYearClass,Code_StatusDataset,Code_Country,Number_ConstructionYearClass,Description_ConstructionYearClass,Description_ConstructionYearClass_National,Remark_ConstructionYearClass,ConstructionYearClass_FirstYear,ConstructionYearClass_LastYear,Code_ConstructionYearClass_National,Date_Entry,Date_Change,Note_DataBaseAdmin
0,code of the construction year period for build...,code of the dataset status,ISO 3166-1-alpha-2 code,serial number of national construction year class,detailed description,"detailed description, national language",internal remark (sources etc.),first year of period (for the first constructi...,last year of period (for the latest constructi...,"national code for construction year class, if ...",date of entry into database,date of last change,note or advice by database administration
1,NaN,NaN,NaN,"consecutive numbers, starting with 1",NaN,NaN,NaN,to be defined according to typical constructio...,to be defined according to typical constructio...,optional,NaN,NaN,implemented / necessary / recommended changes
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,Tab.Const.StatusDataset,Tab.Const.Country,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,VarChar,VarChar,VarChar,Integer,Text,Text,Text,Integer,Integer,VarChar,Date,Date,Text

First column name: 'Code_ConstructionYearClass'

Sample values from first column:
0     code of the construction year period for build...
1                                                   NaN
2                                                   NaN
3                                                   NaN
4                                               VarChar
5                                                   NaN
6                                                   NaN
7                                                   NaN
8                                                   NaN
9                                                 ##.01
10                                                ##.02
11                                                ##.03
12                                                DE.00
13                                                DE.01
14                                                DE.02
15                                                DE.03
16                                                DE.04
17                                                DE.05
18                                                DE.06
19                                                DE.07
Name: Code_ConstructionYearClass, dtype: object

Count of rows starting with 'DE.':
  Rows starting with 'DE.': 13
  Total rows: 169

Filtered data for Germany:
  Original rows: 169
  Germany rows: 13
  Columns: 13

Sample of filtered first column values:
['DE.00', 'DE.01', 'DE.02', 'DE.03', 'DE.04', 'DE.05', 'DE.06', 'DE.07', 'DE.08', 'DE.09']

Sample of Germany Construction Year Class data:
DataFrame shape: (13, 13)

   Code_ConstructionYearClass Code_StatusDataset Code_Country  \
12                      DE.00           Typology           DE
13                      DE.01           Typology           DE
14                      DE.02           Typology           DE
15                      DE.03           Typology           DE
16                      DE.04           Typology           DE
17                      DE.05           Typology           DE
18                      DE.06           Typology           DE
19                      DE.07           Typology           DE
20                      DE.08           Typology           DE
21                      DE.09           Typology           DE

   Number_ConstructionYearClass Description_ConstructionYearClass  \
12                            0                               NaN
13                            1                               NaN
14                            2                               NaN
15                            3                               NaN
16                            4                               NaN
17                            5                               NaN
18                            6                               NaN
19                            7                               NaN
20                            8                               NaN
21                            9                               NaN

           Description_ConstructionYearClass_National  \
12                                                NaN
13                                                NaN
14                                                NaN
15                                                NaN
16                                                NaN
17                                                NaN
18                                                NaN
19                                                NaN
20  Wärmeschutzverordnung 1984 (national requireme...
21  Wärmeschutzverordnung 1995 (national requireme...

                         Remark_ConstructionYearClass  \
12  auxiliary dataset; construction year class not...
13                                                NaN
14                                                NaN
15                                                NaN
16                                                NaN
17                                                NaN
18                                                NaN
19                                                NaN
20                                                NaN
21                                                NaN

   ConstructionYearClass_FirstYear ConstructionYearClass_LastYear  \
12                               0                              0
13                               0                           1859
14                            1860                           1918
15                            1919                           1948
16                            1949                           1957
17                            1958                           1968
18                            1969                           1978
19                            1979                           1983
20                            1984                           1994
21                            1995                           2001

   Code_ConstructionYearClass_National           Date_Entry Date_Change  \
12                                 NaN  2013-03-27 00:00:00         NaN
13                                   A  2010-09-07 00:00:00         NaN
14                                   B  2010-09-07 00:00:00         NaN
15                                   C  2010-09-07 00:00:00         NaN
16                                   D  2010-09-07 00:00:00         NaN
17                                   E  2010-09-07 00:00:00         NaN
18                                   F  2010-09-07 00:00:00         NaN
19                                   G  2010-09-07 00:00:00         NaN
20                                   H  2010-09-07 00:00:00         NaN
21                                   I  2010-09-07 00:00:00         NaN

   Note_DataBaseAdmin
12                NaN
13                NaN
14                NaN
15                NaN
16                NaN
17                NaN
18                NaN
19                NaN
20                NaN
21                NaN

In [22]:
# Save the extracted Construction Year Class data as CSV
try:
    output_dir = Path("/mnt/d/heatpump_data/u_values")
    output_dir.mkdir(parents=True, exist_ok=True)
    
    # Save as CSV
    csv_path = output_dir / "germany_constr_year_class.csv"
    df_year_de.to_csv(csv_path, index=False)
    print(f"Saved CSV to: {csv_path}")
    
    print(f"\nSummary:")
    print(f"  Total rows: {len(df_year_de)}")
    print(f"  Total columns: {len(df_year_de.columns)}")
except NameError:
    print("No data to save. Please run the filtering cell first.")

Saved CSV to: /mnt/d/heatpump_data/u_values/germany_constr_year_class.csv

Summary:
  Total rows: 13
  Total columns: 13

In [23]:
# Display column information
try:
    print("All columns in Germany Construction Year Class dataset:")
    for idx, col in enumerate(df_year_de.columns, 1):
        non_null_count = df_year_de[col].notna().sum()
        print(f"{idx:3d}. {col:50s} - Non-null values: {non_null_count}/{len(df_year_de)}")
except NameError:
    print("Please run the filtering cell first to create df_year_de.")

All columns in Germany Construction Year Class dataset:
  1. Code_ConstructionYearClass                         - Non-null values: 13/13
  2. Code_StatusDataset                                 - Non-null values: 13/13
  3. Code_Country                                       - Non-null values: 13/13
  4. Number_ConstructionYearClass                       - Non-null values: 13/13
  5. Description_ConstructionYearClass                  - Non-null values: 0/13
  6. Description_ConstructionYearClass_National         - Non-null values: 5/13
  7. Remark_ConstructionYearClass                       - Non-null values: 1/13
  8. ConstructionYearClass_FirstYear                    - Non-null values: 13/13
  9. ConstructionYearClass_LastYear                     - Non-null values: 13/13
 10. Code_ConstructionYearClass_National                - Non-null values: 12/13
 11. Date_Entry                                         - Non-null values: 13/13
 12. Date_Change                                        - Non-null values: 1/13
 13. Note_DataBaseAdmin                                 - Non-null values: 0/13